--- #YAML:1.0
name:               Module-Install-TestTarget
version:            0.12
abstract:           Assembles test targets for `make` with code snippets
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::Install:    1.43
    ExtUtils::MakeMaker:  6.31
    Module::Install:      1
    Test::More:           0.96
    Test::Requires:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
